pipeline {
    	    
	def buildenv = docker.image('maven:3-alpine')
	buildenv.pull()
	buildenv.inside {
		def server = Artifactory.server('artifactory1')

		stage('Build') {
		timeout(10)
			{ 
  		 		def rtMaven = Artifactory.newMavenBuild()
		 		rtMaven.resolver server: server, releaseRepo: 'libs-release', snapshotRepo: 'libs-snapshot'
		 		rtMaven.deployer server: server, releaseRepo: 'libs-release-local', snapshotRepo: 'libs-snapshot-local'
                 		def buildInfo = rtMaven.run pom: 'pom.xml', goals: 'clean install'			
			}
		}	
	}

}
